services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    image: euhandev/milky.server:latest
    container_name: milky.server
    restart: unless-stopped
    ports:
      - '5000:5000'
    env_file:
      - .env
    depends_on:
      - mongo

  mongo:
    image: mongo:latest
    container_name: milky.server-mongo
    restart: unless-stopped
    # ports:
    #   - '27017:27017'
    volumes:
      - mongo_data:/data/db

  mongo-express:
    image: mongo-express:latest
    container_name: milky.server-mongo-express
    restart: unless-stopped
    # ports:
    #   - '8081:8081'
    depends_on:
      - mongo

volumes:
  mongo_data:
