import {
  LayoutDashboard,
  ShoppingBag,
  Monitor,
  QrCode,
  Grid,
  BookOpen,
  ChefHat,
  Wine,
  Package,
  Users,
  UserCheck,
  BarChart3,
  Sparkles,
  Bell,
  Settings,
} from 'lucide-react';
import {
  ManagerNavItem,
  ManagerProfile,
  AIOperationsSummary,
  OperationKPICard,
  QuickActionItem,
  LiveOrder,
  SmartAlert,
  FloorStatusItem,
  KitchenOpsSummary,
  HealthMetric,
  POSCategory,
  POSProductItem,
  POSCartItem,
  TableQRItem,
  QRStatsData,
  QRHourlyScan,
  QRSettingsState,
  FloorTable,
  TablesKPIStats,
  MenuCategoryFilter,
  ManagerMenuItem,
  InventoryCategoryFilter,
  InventoryItem,
  InventoryKPIsData,
  StaffMember,
  StaffKPIsData,
  ManagerCustomer,
  CustomerKPIsData,
} from './types';

export const managerNavItems: ManagerNavItem[] = [
  { name: 'Dashboard', href: '/manager-dashboard', icon: LayoutDashboard },
  { name: 'Live Orders', href: '/manager-dashboard?tab=live-orders', icon: ShoppingBag, badge: '5', badgeColor: 'bg-amber-500/20 text-amber-400' },
  { name: 'POS', href: '/manager-dashboard?tab=pos', icon: Monitor },
  { name: 'QR Ordering', href: '/manager-dashboard?tab=qr-ordering', icon: QrCode },
  { name: 'Tables', href: '/manager-dashboard?tab=tables', icon: Grid },
  { name: 'Menu', href: '/manager-dashboard?tab=menu', icon: BookOpen },
  { name: 'Kitchen Display', href: '/manager-dashboard?tab=kitchen-display', icon: ChefHat },
  { name: 'Bar Display', href: '/manager-dashboard?tab=bar-display', icon: Wine },
  { name: 'Inventory', href: '/manager-dashboard?tab=inventory', icon: Package },
  { name: 'Staff', href: '/manager-dashboard?tab=staff', icon: Users, badge: '21', badgeColor: 'bg-emerald-500/20 text-emerald-400' },
  { name: 'Customers', href: '/manager-dashboard?tab=customers', icon: UserCheck },
  { name: 'Reports', href: '/manager-dashboard?tab=reports', icon: BarChart3 },
  { name: 'AI Insights', href: '/manager-dashboard?tab=ai-insights', icon: Sparkles },
  { name: 'Notifications', href: '/manager-dashboard?tab=notifications', icon: Bell, badge: '4', badgeColor: 'bg-red-500/20 text-red-400' },
  { name: 'Settings', href: '/manager-dashboard?tab=settings', icon: Settings },
];

export const initialManagerProfile: ManagerProfile = {
  name: 'Sarah Johnson',
  email: 'Manager@.com',
  role: 'General Manager',
  branch: 'Downtown Branch',
  company: 'Tavonza Group',
};

export const initialOperationsSummary: AIOperationsSummary = {
  score: 94,
  rating: 'Excellent',
  description:
    'Your restaurant is operating at 94% efficiency. Lunch demand is expected to increase by 18% within the next hour. Three orders are at risk of delay, Floor 2 is approaching full capacity — assigning one additional waiter and restocking mozzarella cheese before dinner service will help maintain service quality.',
  recommendations: [
    'Assign waiter to Floor 2',
    'Prioritize 3 delayed orders',
    'Restock mozzarella',
    'Send review requests',
  ],
};

export const initialKPICards: OperationKPICard[] = [
  {
    id: 'kpi-1',
    title: 'Active Orders',
    value: '42',
    subtitle: '8 New Orders',
    iconColor: 'text-blue-500',
    iconBg: 'bg-blue-500/10',
    color: 'text-white',
  },
  {
    id: 'kpi-2',
    title: 'Tables Occupied',
    value: '18/24',
    subtitle: '75% Occupancy',
    iconColor: 'text-amber-500',
    iconBg: 'bg-amber-500/10',
    color: 'text-white',
  },
  {
    id: 'kpi-3',
    title: 'Guests Served',
    value: '186',
    subtitle: 'Today',
    iconColor: 'text-emerald-500',
    iconBg: 'bg-emerald-500/10',
    color: 'text-white',
  },
  {
    id: 'kpi-4',
    title: 'Staff On Duty',
    value: '21',
    subtitle: '18 Active · 3 Break',
    iconColor: 'text-violet-500',
    iconBg: 'bg-violet-500/10',
    color: 'text-white',
  },
  {
    id: 'kpi-5',
    title: 'Kitchen Queue',
    value: '14',
    subtitle: 'Avg. 13 min prep',
    iconColor: 'text-orange-500',
    iconBg: 'bg-orange-500/10',
    color: 'text-white',
  },
  {
    id: 'kpi-6',
    title: 'Satisfaction',
    value: '4.8',
    subtitle: "Today's Rating",
    iconColor: 'text-yellow-500',
    iconBg: 'bg-yellow-500/10',
    color: 'text-white',
  },
];

export const quickActionList: QuickActionItem[] = [
  { id: 'qa-1', label: 'New Order', iconName: 'Plus' },
  { id: 'qa-2', label: 'Assign Table', iconName: 'Grid' },
  { id: 'qa-3', label: 'Update Menu', iconName: 'Utensils' },
  { id: 'qa-4', label: 'Kitchen', iconName: 'ChefHat' },
  { id: 'qa-5', label: 'Staff', iconName: 'Users' },
  { id: 'qa-6', label: 'Inventory', iconName: 'Package' },
  { id: 'qa-7', label: 'Reports', iconName: 'BarChart' },
  { id: 'qa-8', label: 'AI Insights', iconName: 'Sparkles' },
];

export const initialLiveOrders: LiveOrder[] = [
  {
    id: 'ord-1',
    orderNumber: '#10482',
    table: 'T-08',
    waiter: 'Emma Wilson',
    status: 'Preparing',
    amount: 46.5,
  },
  {
    id: 'ord-2',
    orderNumber: '#10483',
    table: 'T-08',
    waiter: 'Emma Wilson',
    status: 'Ready',
    amount: 46.5,
  },
  {
    id: 'ord-3',
    orderNumber: '#10484',
    table: 'T-08',
    waiter: 'Emma Wilson',
    status: 'Preparing',
    amount: 46.5,
  },
  {
    id: 'ord-4',
    orderNumber: '#10485',
    table: 'T-08',
    waiter: 'Emma Wilson',
    status: 'Preparing',
    amount: 46.5,
  },
  {
    id: 'ord-5',
    orderNumber: '#10486',
    table: 'T-08',
    waiter: 'Emma Wilson',
    status: 'Preparing',
    amount: 46.5,
  },
];

export const initialSmartAlerts: SmartAlert[] = [
  {
    id: 'alt-1',
    message: 'Table 12 has been waiting for 18 minutes.',
    timeAgo: '2 min ago',
    severity: 'danger',
  },
  {
    id: 'alt-2',
    message: 'Kitchen preparation time has increased by 9%.',
    timeAgo: '2 min ago',
    severity: 'warning',
  },
  {
    id: 'alt-3',
    message: 'Soft drinks inventory is below minimum stock level.',
    timeAgo: '2 min ago',
    severity: 'caution',
  },
  {
    id: 'alt-4',
    message: 'VIP customer has checked in.',
    timeAgo: '2 min ago',
    severity: 'success',
  },
];

export const initialFloorStatus: FloorStatusItem[] = [
  {
    status: 'Available',
    count: 6,
    color: 'text-teal-400',
    bg: 'bg-gray-900/50',
  },
  {
    status: 'Occupied',
    count: 18,
    color: 'text-blue-500',
    bg: 'bg-slate-900',
  },
  {
    status: 'Reserved',
    count: 3,
    color: 'text-amber-500',
    bg: 'bg-stone-800',
  },
  {
    status: 'Cleaning',
    count: 2,
    color: 'text-zinc-400',
    bg: 'bg-gray-900',
  },
];

export const initialKitchenOps: KitchenOpsSummary = {
  queueCount: 14,
  delayedCount: 3,
  completedCount: 132,
  avgTime: '13m',
  stationAlert:
    'Grill Station nearing capacity. Reassign one order to Fry Station.',
};

export const initialHealthMetrics: HealthMetric[] = [
  { label: 'Service Speed', score: 96, color: 'bg-emerald-500' },
  { label: 'Kitchen Efficiency', score: 92, color: 'bg-blue-500' },
  { label: 'Staff Availability', score: 95, color: 'bg-emerald-500' },
  { label: 'Table Turnover', score: 91, color: 'bg-blue-500' },
  { label: 'Customer Satisfaction', score: 94, color: 'bg-blue-500' },
];

export const initialLiveOrdersKPIData: {
  activeOrders: number;
  activeOrdersSubtitle: string;
  avgWaitTime: string;
  avgWaitTimeSubtitle: string;
  delayedOrders: number;
  delayedOrdersSubtitle: string;
  revenueToday: string;
  revenueTodaySubtitle: string;
} = {
  activeOrders: 42,
  activeOrdersSubtitle: '8 new in last hour',
  avgWaitTime: '13m',
  avgWaitTimeSubtitle: '↓ 2 min vs yesterday',
  delayedOrders: 3,
  delayedOrdersSubtitle: 'Needs attention',
  revenueToday: '$4,280',
  revenueTodaySubtitle: '↑ 12% vs yesterday',
};

export const menuItemsList = [
  { id: 'm-1', name: 'Margherita Pizza', price: 18.0 },
  { id: 'm-2', name: 'Pepperoni Pizza', price: 21.0 },
  { id: 'm-3', name: 'BBQ Chicken Burger', price: 15.5 },
  { id: 'm-4', name: 'Caesar Salad', price: 11.0 },
  { id: 'm-5', name: 'Grilled Salmon', price: 26.0 },
  { id: 'm-6', name: 'Ribeye Steak', price: 38.0 },
];

export const tableList = [
  'T-01',
  'T-02',
  'T-03',
  'T-04',
  'T-05',
  'T-06',
  'T-07',
  'T-08',
  'T-09',
  'T-10',
  'T-12',
  'T-14',
  'T-16',
  'T-18',
];

export const waiterList = [
  'Emma Wilson',
  'Sarah Johnson',
  'David Chen',
  'Marcus Brody',
  'Elena Rostova',
];

export const initialDetailedLiveOrders = [
  {
    id: 'ord-101',
    orderNumber: '#10482',
    table: 'T-08',
    waiter: 'Emma Wilson',
    itemsCount: 4,
    itemsSummary: '4 items',
    total: 48.5,
    status: 'Preparing' as const,
    eta: '8 min',
    time: '12:42 PM',
    notes: 'Gluten-free crust on Margherita if possible',
    orderItems: [
      { id: 'oi-1', name: 'Margherita Pizza', price: 18.0, quantity: 1 },
      { id: 'oi-2', name: 'Pepperoni Pizza', price: 21.0, quantity: 1 },
      { id: 'oi-3', name: 'Caesar Salad', price: 11.0, quantity: 1 },
    ],
  },
  {
    id: 'ord-102',
    orderNumber: '#10483',
    table: 'T-02',
    waiter: 'Emma Wilson',
    itemsCount: 4,
    itemsSummary: '4 items',
    total: 48.5,
    status: 'Preparing' as const,
    eta: '8 min',
    time: '12:42 PM',
    notes: 'Extra parmesan on side',
    orderItems: [
      { id: 'oi-4', name: 'BBQ Chicken Burger', price: 15.5, quantity: 2 },
      { id: 'oi-5', name: 'Caesar Salad', price: 11.0, quantity: 1 },
    ],
  },
  {
    id: 'ord-103',
    orderNumber: '#10484',
    table: 'T-05',
    waiter: 'David Chen',
    itemsCount: 4,
    itemsSummary: '4 items',
    total: 48.5,
    status: 'Preparing' as const,
    eta: '8 min',
    time: '12:42 PM',
    notes: 'Medium rare steak',
    orderItems: [
      { id: 'oi-6', name: 'Ribeye Steak', price: 38.0, quantity: 1 },
      { id: 'oi-7', name: 'Caesar Salad', price: 11.0, quantity: 1 },
    ],
  },
  {
    id: 'ord-104',
    orderNumber: '#10485',
    table: 'T-08',
    waiter: 'Emma Wilson',
    itemsCount: 4,
    itemsSummary: '4 items',
    total: 48.5,
    status: 'Preparing' as const,
    eta: '8 min',
    time: '12:42 PM',
    notes: '',
    orderItems: [
      { id: 'oi-8', name: 'Grilled Salmon', price: 26.0, quantity: 1 },
      { id: 'oi-9', name: 'Pepperoni Pizza', price: 21.0, quantity: 1 },
    ],
  },
  {
    id: 'ord-105',
    orderNumber: '#10486',
    table: 'T-04',
    waiter: 'Elena Rostova',
    itemsCount: 4,
    itemsSummary: '4 items',
    total: 48.5,
    status: 'Cooking' as const,
    eta: '12 min',
    time: '12:40 PM',
    notes: 'Urgent for Table 4',
    orderItems: [
      { id: 'oi-10', name: 'Ribeye Steak', price: 38.0, quantity: 1 },
      { id: 'oi-11', name: 'Caesar Salad', price: 11.0, quantity: 1 },
    ],
  },
  {
    id: 'ord-106',
    orderNumber: '#10487',
    table: 'T-01',
    waiter: 'Emma Wilson',
    itemsCount: 2,
    itemsSummary: '2 items',
    total: 36.5,
    status: 'Waiting' as const,
    eta: '18 min',
    time: '12:48 PM',
    notes: 'Water with lemon',
    orderItems: [
      { id: 'oi-12', name: 'Pepperoni Pizza', price: 21.0, quantity: 1 },
      { id: 'oi-13', name: 'BBQ Chicken Burger', price: 15.5, quantity: 1 },
    ],
  },
  {
    id: 'ord-107',
    orderNumber: '#10488',
    table: 'T-08',
    waiter: 'Emma Wilson',
    itemsCount: 4,
    itemsSummary: '4 items',
    total: 48.5,
    status: 'Ready' as const,
    eta: 'Ready',
    time: '12:35 PM',
    notes: '',
    orderItems: [
      { id: 'oi-14', name: 'Margherita Pizza', price: 18.0, quantity: 2 },
      { id: 'oi-15', name: 'Caesar Salad', price: 11.0, quantity: 1 },
    ],
  },
  {
    id: 'ord-108',
    orderNumber: '#10489',
    table: 'T-06',
    waiter: 'Marcus Brody',
    itemsCount: 3,
    itemsSummary: '3 items',
    total: 52.0,
    status: 'Served' as const,
    eta: 'Served',
    time: '12:30 PM',
    notes: '',
    orderItems: [
      { id: 'oi-16', name: 'Grilled Salmon', price: 26.0, quantity: 2 },
    ],
  },
  {
    id: 'ord-109',
    orderNumber: '#10490',
    table: 'T-08',
    waiter: 'Emma Wilson',
    itemsCount: 4,
    itemsSummary: '4 items',
    total: 48.5,
    status: 'Preparing' as const,
    eta: '8 min',
    time: '12:42 PM',
    notes: '',
    orderItems: [
      { id: 'oi-17', name: 'Pepperoni Pizza', price: 21.0, quantity: 2 },
    ],
  },
  {
    id: 'ord-110',
    orderNumber: '#10491',
    table: 'T-03',
    waiter: 'David Chen',
    itemsCount: 2,
    itemsSummary: '2 items',
    total: 44.0,
    status: 'Paid' as const,
    eta: 'Completed',
    time: '12:20 PM',
    notes: 'Receipt emailed',
    orderItems: [
      { id: 'oi-18', name: 'Margherita Pizza', price: 18.0, quantity: 1 },
      { id: 'oi-19', name: 'Grilled Salmon', price: 26.0, quantity: 1 },
    ],
  },
  {
    id: 'ord-111',
    orderNumber: '#10492',
    table: 'T-08',
    waiter: 'Emma Wilson',
    itemsCount: 4,
    itemsSummary: '4 items',
    total: 48.5,
    status: 'Preparing' as const,
    eta: '8 min',
    time: '12:42 PM',
    notes: '',
    orderItems: [
      { id: 'oi-20', name: 'BBQ Chicken Burger', price: 15.5, quantity: 2 },
      { id: 'oi-21', name: 'Caesar Salad', price: 11.0, quantity: 1 },
    ],
  },
  {
    id: 'ord-112',
    orderNumber: '#10493',
    table: 'T-09',
    waiter: 'Elena Rostova',
    itemsCount: 1,
    itemsSummary: '1 item',
    total: 38.0,
    status: 'Cooking' as const,
    eta: '14 min',
    time: '12:41 PM',
    notes: 'Well done',
    orderItems: [
      { id: 'oi-22', name: 'Ribeye Steak', price: 38.0, quantity: 1 },
    ],
  },
  {
    id: 'ord-113',
    orderNumber: '#10494',
    table: 'T-08',
    waiter: 'Emma Wilson',
    itemsCount: 4,
    itemsSummary: '4 items',
    total: 48.5,
    status: 'Preparing' as const,
    eta: '8 min',
    time: '12:42 PM',
    notes: '',
    orderItems: [
      { id: 'oi-23', name: 'Margherita Pizza', price: 18.0, quantity: 1 },
      { id: 'oi-24', name: 'Caesar Salad', price: 11.0, quantity: 1 },
    ],
  },
  {
    id: 'ord-114',
    orderNumber: '#10495',
    table: 'T-10',
    waiter: 'David Chen',
    itemsCount: 3,
    itemsSummary: '3 items',
    total: 55.0,
    status: 'Ready' as const,
    eta: 'Ready',
    time: '12:36 PM',
    notes: 'Ready for pickup',
    orderItems: [
      { id: 'oi-25', name: 'Pepperoni Pizza', price: 21.0, quantity: 1 },
      { id: 'oi-26', name: 'Grilled Salmon', price: 26.0, quantity: 1 },
    ],
  },
  {
    id: 'ord-115',
    orderNumber: '#10496',
    table: 'T-08',
    waiter: 'Emma Wilson',
    itemsCount: 4,
    itemsSummary: '4 items',
    total: 48.5,
    status: 'Preparing' as const,
    eta: '8 min',
    time: '12:42 PM',
    notes: '',
    orderItems: [
      { id: 'oi-27', name: 'Margherita Pizza', price: 18.0, quantity: 1 },
      { id: 'oi-28', name: 'Pepperoni Pizza', price: 21.0, quantity: 1 },
    ],
  },
];

// ==========================================
// Point of Sale (POS) Data
// ==========================================
export const posCategories: POSCategory[] = [
  'All',
  'Burgers',
  'Pizza',
  'Pasta',
  'Salads',
  'Desserts',
  'Drinks',
];

export const initialPOSProducts: POSProductItem[] = [
  {
    id: 'pos-1',
    name: 'Smokey Salmon',
    category: 'All',
    subcategory: 'Rolls',
    price: 18.50,
    image: 'https://images.unsplash.com/photo-1579871494447-9811cf80d66c?auto=format&fit=crop&w=600&q=80',
    isHot: true,
    emoji: '🍣',
  },
  {
    id: 'pos-2',
    name: 'Classic Burger',
    category: 'Burgers',
    subcategory: 'Burgers',
    price: 18.50,
    image: 'https://images.unsplash.com/photo-1568901346375-23c9450c58cd?auto=format&fit=crop&w=600&q=80',
    isHot: true,
    emoji: '🍔',
  },
  {
    id: 'pos-3',
    name: 'Mini Pancakes',
    category: 'Desserts',
    subcategory: 'Pancakes',
    price: 18.50,
    image: 'https://images.unsplash.com/photo-1528207776546-365bb710ee93?auto=format&fit=crop&w=600&q=80',
    isHot: false,
    emoji: '🥞',
  },
  {
    id: 'pos-4',
    name: 'Sushi Rolls',
    category: 'All',
    subcategory: 'Rolls',
    price: 18.50,
    image: 'https://images.unsplash.com/photo-1611143669185-af224c5e3252?auto=format&fit=crop&w=600&q=80',
    isHot: true,
    emoji: '🍱',
  },
  {
    id: 'pos-5',
    name: 'Margherita Pizza',
    category: 'Pizza',
    subcategory: 'Pizza',
    price: 19.50,
    image: 'https://images.unsplash.com/photo-1513104890138-7c749659a591?auto=format&fit=crop&w=600&q=80',
    isHot: false,
    emoji: '🍕',
  },
  {
    id: 'pos-6',
    name: 'Greek Salad',
    category: 'Salads',
    subcategory: 'Salads',
    price: 13.00,
    image: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=600&q=80',
    isHot: false,
    emoji: '🥗',
  },
  {
    id: 'pos-7',
    name: 'Truffle Pasta',
    category: 'Pasta',
    subcategory: 'Pasta',
    price: 22.00,
    image: 'https://images.unsplash.com/photo-1621996346565-e3d5d6281691?auto=format&fit=crop&w=600&q=80',
    isHot: true,
    emoji: '🍝',
  },
  {
    id: 'pos-8',
    name: 'Double Cheeseburger',
    category: 'Burgers',
    subcategory: 'Burgers',
    price: 19.00,
    image: 'https://images.unsplash.com/photo-1586190848861-99aa4a171e90?auto=format&fit=crop&w=600&q=80',
    isHot: true,
    emoji: '🍔',
  },
  {
    id: 'pos-9',
    name: 'Pepperoni Passion',
    category: 'Pizza',
    subcategory: 'Pizza',
    price: 21.50,
    image: 'https://images.unsplash.com/photo-1604382354936-07c5d9983bd3?auto=format&fit=crop&w=600&q=80',
    isHot: true,
    emoji: '🍕',
  },
  {
    id: 'pos-10',
    name: 'Penne Arrabbiata',
    category: 'Pasta',
    subcategory: 'Pasta',
    price: 17.50,
    image: 'https://images.unsplash.com/photo-1551183053-bf91a1d81141?auto=format&fit=crop&w=600&q=80',
    isHot: false,
    emoji: '🍝',
  },
  {
    id: 'pos-11',
    name: 'Caesar Chicken Salad',
    category: 'Salads',
    subcategory: 'Salads',
    price: 14.50,
    image: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&w=600&q=80',
    isHot: false,
    emoji: '🥗',
  },
  {
    id: 'pos-12',
    name: 'Tiramisu Classico',
    category: 'Desserts',
    subcategory: 'Desserts',
    price: 9.50,
    image: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=600&q=80',
    isHot: false,
    emoji: '🍰',
  },
  {
    id: 'pos-13',
    name: 'Berry Mojito',
    category: 'Drinks',
    subcategory: 'Drinks',
    price: 8.50,
    image: 'https://images.unsplash.com/photo-1513558161293-cdaf765ed2fd?auto=format&fit=crop&w=600&q=80',
    isHot: false,
    emoji: '🍹',
  },
  {
    id: 'pos-14',
    name: 'Iced Caramel Latte',
    category: 'Drinks',
    subcategory: 'Drinks',
    price: 6.50,
    image: 'https://images.unsplash.com/photo-1517256064527-09c73fc73e38?auto=format&fit=crop&w=600&q=80',
    isHot: false,
    emoji: '☕',
  },
  {
    id: 'pos-15',
    name: 'Chocolate Lava Cake',
    category: 'Desserts',
    subcategory: 'Desserts',
    price: 10.50,
    image: 'https://images.unsplash.com/photo-1606313564200-e75d5e30476c?auto=format&fit=crop&w=600&q=80',
    isHot: true,
    emoji: '🍫',
  },
  {
    id: 'pos-16',
    name: 'Craft Lemonade',
    category: 'Drinks',
    subcategory: 'Drinks',
    price: 5.50,
    image: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=600&q=80',
    isHot: false,
    emoji: '🍋',
  },
];

export const initialPOSCart: POSCartItem[] = [
  {
    product: initialPOSProducts[4], // Margherita Pizza
    quantity: 2,
  },
  {
    product: initialPOSProducts[5], // Greek Salad
    quantity: 1,
  },
];

// ==========================================
// QR Ordering Data
// ==========================================
export const initialQRStats: QRStatsData = {
  activeQRCodes: 24,
  activeSubtitle: 'All tables covered',
  scansToday: 17,
  scansGrowth: '↑ 23% vs yesterday',
  ordersViaQRPercent: 64,
  ordersSubtitle: 'of total orders',
  avgOrderValue: 38.40,
  avgSubtitle: 'via QR ordering',
};

export const initialTableQRCodes: TableQRItem[] = [
  {
    id: 'qr-t1',
    tableNumber: 'T-01',
    seats: 2,
    area: 'Main Hall',
    status: 'Active',
    language: 'English',
    scansToday: 14,
    lastScanTime: '12:45 PM',
  },
  {
    id: 'qr-t2',
    tableNumber: 'T-02',
    seats: 2,
    area: 'Main Hall',
    status: 'Active',
    language: 'English',
    scansToday: 11,
    lastScanTime: '12:30 PM',
  },
  {
    id: 'qr-t3',
    tableNumber: 'T-03',
    seats: 4,
    area: 'Main Hall',
    status: 'Active',
    language: 'Dutch',
    scansToday: 8,
    lastScanTime: '12:15 PM',
  },
  {
    id: 'qr-t4',
    tableNumber: 'T-04',
    seats: 4,
    area: 'Main Hall',
    status: 'Active',
    language: 'English',
    scansToday: 15,
    lastScanTime: '1:02 PM',
  },
  {
    id: 'qr-t5',
    tableNumber: 'T-05',
    seats: 6,
    area: 'VIP Terrace',
    status: 'Active',
    language: 'English',
    scansToday: 19,
    lastScanTime: '1:10 PM',
  },
  {
    id: 'qr-t6',
    tableNumber: 'T-06',
    seats: 2,
    area: 'Bar Area',
    status: 'Active',
    language: 'German',
    scansToday: 7,
    lastScanTime: '11:50 AM',
  },
  {
    id: 'qr-t7',
    tableNumber: 'T-07',
    seats: 4,
    area: 'Patio Garden',
    status: 'Active',
    language: 'French',
    scansToday: 12,
    lastScanTime: '12:55 PM',
  },
  {
    id: 'qr-t8',
    tableNumber: 'T-08',
    seats: 8,
    area: 'Banquet Room',
    status: 'Active',
    language: 'English',
    scansToday: 22,
    lastScanTime: '1:15 PM',
  },
];

export const initialQRHourlyScans: QRHourlyScan[] = [
  { time: '10AM', scans: 12 },
  { time: '11AM', scans: 18 },
  { time: '12PM', scans: 14 },
  { time: '1PM', scans: 32 },
  { time: '2PM', scans: 48 },
  { time: '3PM', scans: 58 },
  { time: '4PM', scans: 50 },
];

export const initialQRSettings: QRSettingsState = {
  autoConfirmOrders: true,
  showAllergenInfo: true,
  allowItemNotes: true,
  upsellSuggestions: false,
  tableSidePayment: true,
};

// ==========================================
// Tables Page Data
// ==========================================
export const initialTablesKPIStats: TablesKPIStats = {
  occupiedText: '16/30',
  occupiedCount: 16,
  totalTables: 30,
  availableCount: 10,
  reservedCount: 4,
  activeRevenue: 1583,
};

export const initialFloorTables: FloorTable[] = [
  {
    id: 'tbl-1',
    tableNumber: 'T-01',
    capacity: 4,
    currentGuests: 4,
    status: 'Occupied',
    waiter: 'Emma',
    seatedTime: '45m',
    section: 'Floor 1',
    location: 'Indoor',
    shape: 'Square',
    notes: 'Ordered mains, requested extra napkins',
  },
  {
    id: 'tbl-2',
    tableNumber: 'T-02',
    capacity: 4,
    currentGuests: 2,
    status: 'Occupied',
    waiter: 'David',
    seatedTime: '20m',
    section: 'Floor 1',
    location: 'Indoor',
    shape: 'Square',
    notes: 'Appetizers served',
  },
  {
    id: 'tbl-3',
    tableNumber: 'T-03',
    capacity: 4,
    currentGuests: 3,
    status: 'Reserved',
    waiter: 'Sarah',
    seatedTime: 'In 15m',
    section: 'Floor 1',
    location: 'Indoor',
    shape: 'Square',
    notes: 'Birthday celebration request',
  },
  {
    id: 'tbl-4',
    tableNumber: 'T-04',
    capacity: 4,
    currentGuests: 4,
    status: 'Occupied',
    waiter: 'Lucas',
    seatedTime: '35m',
    section: 'Floor 1',
    location: 'Indoor',
    shape: 'Square',
    notes: 'Wine pairing course',
  },
  {
    id: 'tbl-5',
    tableNumber: 'T-05',
    capacity: 4,
    currentGuests: 4,
    status: 'Occupied',
    waiter: 'Emma',
    seatedTime: '1h 10m',
    section: 'Floor 1',
    location: 'Window',
    shape: 'Square',
    notes: 'Dessert menu handed',
  },
  {
    id: 'tbl-6',
    tableNumber: 'T-06',
    capacity: 8,
    currentGuests: 8,
    status: 'Reserved',
    waiter: 'David',
    seatedTime: 'In 30m',
    section: 'Floor 1',
    location: 'VIP Area',
    shape: 'Rectangle',
    notes: 'VIP Executive group dining',
  },
  {
    id: 'tbl-7',
    tableNumber: 'T-07',
    capacity: 4,
    currentGuests: 3,
    status: 'Reserved',
    waiter: 'Lucas',
    seatedTime: 'In 45m',
    section: 'Floor 1',
    location: 'Window',
    shape: 'Square',
    notes: 'High chair needed',
  },
  {
    id: 'tbl-8',
    tableNumber: 'T-08',
    capacity: 4,
    currentGuests: 4,
    status: 'Occupied',
    waiter: 'Sarah',
    seatedTime: '55m',
    section: 'Floor 1',
    location: 'Indoor',
    shape: 'Square',
    notes: 'Bill requested',
  },
  {
    id: 'tbl-9',
    tableNumber: 'T-09',
    capacity: 2,
    currentGuests: 0,
    status: 'Available',
    waiter: 'Unassigned',
    seatedTime: '-',
    section: 'Floor 1',
    location: 'Bar Area',
    shape: 'Round',
    notes: 'Cleaned and sanitized',
  },
  {
    id: 'tbl-10',
    tableNumber: 'T-10',
    capacity: 2,
    currentGuests: 0,
    status: 'Available',
    waiter: 'Unassigned',
    seatedTime: '-',
    section: 'Floor 1',
    location: 'Bar Area',
    shape: 'Round',
    notes: 'Cleaned and sanitized',
  },
  {
    id: 'tbl-11',
    tableNumber: 'T-11',
    capacity: 4,
    currentGuests: 0,
    status: 'Available',
    waiter: 'Unassigned',
    seatedTime: '-',
    section: 'Floor 1',
    location: 'Terrace',
    shape: 'Square',
    notes: 'Ready for seating',
  },
  {
    id: 'tbl-12',
    tableNumber: 'T-12',
    capacity: 6,
    currentGuests: 0,
    status: 'Available',
    waiter: 'Unassigned',
    seatedTime: '-',
    section: 'Floor 1',
    location: 'Terrace',
    shape: 'Rectangle',
    notes: 'Outdoor heating on',
  },
  {
    id: 'tbl-13',
    tableNumber: 'T-13',
    capacity: 4,
    currentGuests: 4,
    status: 'Occupied',
    waiter: 'David',
    seatedTime: '15m',
    section: 'Floor 1',
    location: 'Indoor',
    shape: 'Square',
    notes: 'Drinks served',
  },
  {
    id: 'tbl-14',
    tableNumber: 'T-14',
    capacity: 2,
    currentGuests: 2,
    status: 'Occupied',
    waiter: 'Emma',
    seatedTime: '25m',
    section: 'Floor 1',
    location: 'Indoor',
    shape: 'Round',
    notes: 'Quick lunch set',
  },
  {
    id: 'tbl-15',
    tableNumber: 'T-15',
    capacity: 4,
    currentGuests: 0,
    status: 'Available',
    waiter: 'Unassigned',
    seatedTime: '-',
    section: 'Floor 1',
    location: 'Indoor',
    shape: 'Square',
    notes: 'Ready for seating',
  },
  {
    id: 'tbl-16',
    tableNumber: 'T-16',
    capacity: 4,
    currentGuests: 0,
    status: 'Available',
    waiter: 'Unassigned',
    seatedTime: '-',
    section: 'Floor 1',
    location: 'Window',
    shape: 'Square',
    notes: 'Ready for seating',
  },
];

// ==========================================
// Menu Management Data
// ==========================================
export const menuFilterTabs: MenuCategoryFilter[] = [
  'All',
  'Sweet',
  'Savory',
  'Pancake',
  'Coffee',
  'Drinks',
];

export const initialManagerMenuItems: ManagerMenuItem[] = [
  {
    id: 'm-1',
    name: 'Margherita Pizza',
    category: 'Pizza',
    price: 15.00,
    status: 'Available',
    isPopular: true,
    description: 'Fresh mozzarella, San Marzano tomato sauce, fresh basil, extra virgin olive oil',
    prepTimeMinutes: 12,
    calories: 720,
    allergens: 'Gluten, Dairy',
  },
  {
    id: 'm-2',
    name: 'Pepperoni Pizza',
    category: 'Pizza',
    price: 18.00,
    status: 'Available',
    isPopular: false,
    description: 'Crispy artisanal pepperoni, spicy tomato sauce, mozzarella, chili flakes',
    prepTimeMinutes: 14,
    calories: 850,
    allergens: 'Gluten, Dairy',
  },
  {
    id: 'm-3',
    name: 'BBQ Chicken Burger',
    category: 'Burgers',
    price: 28.00,
    status: 'Available',
    isPopular: true,
    description: 'Smoked pulled BBQ chicken breast, cheddar, crispy onion rings, chipotle mayo',
    prepTimeMinutes: 15,
    calories: 920,
    allergens: 'Gluten, Dairy',
  },
  {
    id: 'm-4',
    name: 'Classic Cheeseburger',
    category: 'Burgers',
    price: 19.00,
    status: 'Unavailable',
    isPopular: false,
    description: 'Prime Angus beef patty, aged cheddar, lettuce, tomato, house secret relish',
    prepTimeMinutes: 12,
    calories: 780,
    allergens: 'Gluten, Dairy',
  },
  {
    id: 'm-5',
    name: 'Caesar Salad',
    category: 'Salads',
    price: 18.00,
    status: 'Available',
    isPopular: false,
    description: 'Crisp romaine lettuce, parmigiano reggiano, garlic croutons, creamy caesar dressing',
    prepTimeMinutes: 8,
    calories: 420,
    allergens: 'Dairy, Egg',
  },
  {
    id: 'm-6',
    name: 'Greek Salad',
    category: 'Salads',
    price: 20.00,
    status: 'Available',
    isPopular: false,
    description: 'Kalamata olives, vine tomatoes, cucumber, bell pepper, authentic Greek feta',
    prepTimeMinutes: 8,
    calories: 380,
    allergens: 'Dairy',
  },
  {
    id: 'm-7',
    name: 'Grilled Salmon',
    category: 'Mains',
    price: 12.00,
    status: 'Available',
    isPopular: true,
    description: 'Pan-seared Atlantic salmon fillet, asparagus, lemon butter reduction, dill',
    prepTimeMinutes: 18,
    calories: 540,
    allergens: 'Fish',
  },
  {
    id: 'm-8',
    name: 'Ribeye Steak',
    category: 'Mains',
    price: 18.00,
    status: 'Available',
    isPopular: true,
    description: '300g grain-fed ribeye, roasted rosemary garlic baby potatoes, chimichurri sauce',
    prepTimeMinutes: 20,
    calories: 880,
    allergens: 'None',
  },
  {
    id: 'm-9',
    name: 'Tiramisu',
    category: 'Desserts',
    price: 14.00,
    status: 'Available',
    isPopular: false,
    description: 'Savoiardi ladyfingers soaked in espresso, mascarpone mousse, Valrhona cocoa dust',
    prepTimeMinutes: 5,
    calories: 480,
    allergens: 'Gluten, Dairy, Egg',
  },
  {
    id: 'm-10',
    name: 'Chocolate Lava Cake',
    category: 'Desserts',
    price: 11.00,
    status: 'Available',
    isPopular: false,
    description: 'Warm molten dark chocolate fondant, bourbon vanilla ice cream, fresh raspberry coulis',
    prepTimeMinutes: 10,
    calories: 620,
    allergens: 'Gluten, Dairy, Egg',
  },
  {
    id: 'm-11',
    name: 'Buttermilk Mini Pancakes',
    category: 'Pancake',
    price: 16.00,
    status: 'Available',
    isPopular: true,
    description: 'Stack of fluffy golden mini pancakes, Canadian maple syrup, whipped butter',
    prepTimeMinutes: 10,
    calories: 510,
    allergens: 'Gluten, Dairy',
  },
  {
    id: 'm-12',
    name: 'Caramel Macchiato',
    category: 'Coffee',
    price: 6.50,
    status: 'Available',
    isPopular: true,
    description: 'Steamed whole milk stained with espresso and drizzled with buttery caramel',
    prepTimeMinutes: 4,
    calories: 190,
    allergens: 'Dairy',
  },
  {
    id: 'm-13',
    name: 'Cold Brew Reserve',
    category: 'Coffee',
    price: 5.50,
    status: 'Available',
    isPopular: false,
    description: '24-hour slow steeped single-origin Ethiopian cold brew served over ice rocks',
    prepTimeMinutes: 2,
    calories: 15,
    allergens: 'None',
  },
  {
    id: 'm-14',
    name: 'Berry Mint Mojito',
    category: 'Drinks',
    price: 8.50,
    status: 'Available',
    isPopular: true,
    description: 'Muddled fresh blackberries and raspberries, lime juice, garden mint, club soda',
    prepTimeMinutes: 5,
    calories: 140,
    allergens: 'None',
  },
];

// ==========================================
// Inventory Management Data
// ==========================================
export const initialInventoryKPIs: InventoryKPIsData = {
  criticalCount: 2,
  criticalSubtitle: 'Immediate reorder needed',
  lowStockCount: 3,
  lowSubtitle: 'Reorder this week',
  healthyCount: 5,
  healthySubtitle: 'Within safe levels',
  totalCount: 10,
  totalSubtitle: 'Tracked categories',
};

export const inventoryCategoryTabs: InventoryCategoryFilter[] = [
  'All',
  'Dairy',
  'Meat',
  'Beverages',
  'Pantry',
  'Seafood',
  'Bakery',
];

export const initialInventoryItems: InventoryItem[] = [
  {
    id: 'inv-1',
    name: 'Margherita Pizza',
    category: 'Dairy',
    currentStockText: '2.4 kg',
    currentStock: 2.4,
    unit: 'kg',
    minLevel: '05kg',
    minLevelValue: 5,
    status: 'Available',
    stockStatus: 'Critical',
    progressPercentage: 25,
    progressColor: 'bg-red-500',
    textColor: 'text-red-500',
    supplier: 'Lactalis Gourmet Dairy',
  },
  {
    id: 'inv-2',
    name: 'Pepperoni Pizza',
    category: 'Meat',
    currentStockText: '4.2 kg',
    currentStock: 4.2,
    unit: 'kg',
    minLevel: '08kg',
    minLevelValue: 8,
    status: 'Available',
    stockStatus: 'Low',
    progressPercentage: 50,
    progressColor: 'bg-orange-500',
    textColor: 'text-orange-500',
    supplier: 'Salumi Charcuterie Co.',
  },
  {
    id: 'inv-3',
    name: 'BBQ Chicken Burger',
    category: 'Beverages',
    currentStockText: '18 cans',
    currentStock: 18,
    unit: 'cans',
    minLevel: '05kg',
    minLevelValue: 24,
    status: 'Available',
    stockStatus: 'Low',
    progressPercentage: 50,
    progressColor: 'bg-orange-500',
    textColor: 'text-orange-500',
    supplier: 'Amsterdam Beverage Hub',
  },
  {
    id: 'inv-4',
    name: 'Classic Cheeseburger',
    category: 'Pantry',
    currentStockText: '1.8 L',
    currentStock: 1.8,
    unit: 'L',
    minLevel: '05kg',
    minLevelValue: 5,
    status: 'Unavailable',
    stockStatus: 'Critical',
    progressPercentage: 22,
    progressColor: 'bg-red-500',
    textColor: 'text-red-500',
    supplier: 'Golden Valley Provisions',
  },
  {
    id: 'inv-5',
    name: 'Caesar Salad',
    category: 'Meat',
    currentStockText: '12 pcs',
    currentStock: 12,
    unit: 'pcs',
    minLevel: '05kg',
    minLevelValue: 5,
    status: 'Available',
    stockStatus: 'Healthy',
    progressPercentage: 75,
    progressColor: 'bg-emerald-500',
    textColor: 'text-emerald-500',
    supplier: 'FarmFresh Poultry Farms',
  },
  {
    id: 'inv-6',
    name: 'Greek Salad',
    category: 'Seafood',
    currentStockText: '8 pcs',
    currentStock: 8,
    unit: 'pcs',
    minLevel: '05kg',
    minLevelValue: 5,
    status: 'Available',
    stockStatus: 'Healthy',
    progressPercentage: 70,
    progressColor: 'bg-emerald-500',
    textColor: 'text-emerald-500',
    supplier: 'North Sea Fisheries',
  },
  {
    id: 'inv-7',
    name: 'Grilled Salmon',
    category: 'Pantry',
    currentStockText: '6 L',
    currentStock: 6,
    unit: 'L',
    minLevel: '05kg',
    minLevelValue: 5,
    status: 'Available',
    stockStatus: 'Healthy',
    progressPercentage: 70,
    progressColor: 'bg-emerald-500',
    textColor: 'text-emerald-500',
    supplier: 'Modena Fine Vinegars',
  },
  {
    id: 'inv-8',
    name: 'Ribeye Steak',
    category: 'Bakery',
    currentStockText: '14 balls',
    currentStock: 14,
    unit: 'balls',
    minLevel: '05kg',
    minLevelValue: 5,
    status: 'Available',
    stockStatus: 'Healthy',
    progressPercentage: 70,
    progressColor: 'bg-emerald-500',
    textColor: 'text-emerald-500',
    supplier: 'Artisanal Flour Works',
  },
  {
    id: 'inv-9',
    name: 'Tiramisu',
    category: 'Beverages',
    currentStockText: '6 bottles',
    currentStock: 6,
    unit: 'bottles',
    minLevel: '05kg',
    minLevelValue: 10,
    status: 'Available',
    stockStatus: 'Low',
    progressPercentage: 35,
    progressColor: 'bg-orange-500',
    textColor: 'text-amber-500',
    supplier: 'Tuscany Spirits & Wines',
  },
  {
    id: 'inv-10',
    name: 'Chocolate Lava Cake',
    category: 'Beverages',
    currentStockText: '3.2 kg',
    currentStock: 3.2,
    unit: 'kg',
    minLevel: '05kg',
    minLevelValue: 5,
    status: 'Available',
    stockStatus: 'Healthy',
    progressPercentage: 65,
    progressColor: 'bg-emerald-500',
    textColor: 'text-emerald-500',
    supplier: 'Belgian Cocoa Roasters',
  },
];

// ==========================================
// Staff Management Mock Data
// ==========================================
export const initialStaffKPIs: StaffKPIsData = {
  onDutyCount: 21,
  onDutySubtitle: '18 active · 3 on break',
  waitersActiveCount: 8,
  waitersSubtitle: 'Covering 18 tables',
  kitchenStaffCount: 6,
  kitchenSubtitle: '2 stations active',
  avgRating: 4.8,
  ratingSubtitle: 'Team performance',
};

export const initialStaffMembers: StaffMember[] = [
  {
    id: 'staff-1',
    firstName: 'Emma',
    lastName: 'Wilson',
    fullName: 'Emma Wilson',
    initials: 'EW',
    role: 'Waiter',
    status: 'Active',
    shift: '8AM – 4PM',
    tablesCount: 4,
    ordersCount: 18,
    rating: 4.9,
    phone: '+1 (555) 234-5678',
    email: 'emma@restaurant.com',
    hourlyRate: 18.0,
    startDate: '2024-03-15',
    emergencyContact: '+1 (555) 987-6543',
  },
  {
    id: 'staff-2',
    firstName: 'Olivia',
    lastName: 'Park',
    fullName: 'Olivia Park',
    initials: 'OP',
    role: 'Waiter',
    status: 'Active',
    shift: '8AM – 4PM',
    tablesCount: 4,
    ordersCount: 16,
    rating: 4.8,
    phone: '+1 (555) 345-6789',
    email: 'olivia.p@restaurant.com',
    hourlyRate: 18.0,
    startDate: '2024-04-01',
    emergencyContact: '+1 (555) 876-5432',
  },
  {
    id: 'staff-3',
    firstName: 'David',
    lastName: 'Chen',
    fullName: 'David Chen',
    initials: 'DC',
    role: 'Waiter',
    status: 'Active',
    shift: '9AM – 5PM',
    tablesCount: 3,
    ordersCount: 14,
    rating: 4.7,
    phone: '+1 (555) 456-7890',
    email: 'david.c@restaurant.com',
    hourlyRate: 17.5,
    startDate: '2024-01-10',
    emergencyContact: '+1 (555) 765-4321',
  },
  {
    id: 'staff-4',
    firstName: 'Lucas',
    lastName: 'Rossi',
    fullName: 'Lucas Rossi',
    initials: 'LR',
    role: 'Waiter',
    status: 'Active',
    shift: '12PM – 8PM',
    tablesCount: 3,
    ordersCount: 12,
    rating: 4.9,
    phone: '+1 (555) 567-8901',
    email: 'lucas.r@restaurant.com',
    hourlyRate: 18.5,
    startDate: '2023-11-20',
    emergencyContact: '+1 (555) 654-3210',
  },
  {
    id: 'staff-5',
    firstName: 'Marco',
    lastName: 'Bellini',
    fullName: 'Marco Bellini',
    initials: 'MB',
    role: 'Chef',
    status: 'Active',
    shift: '7AM – 3PM',
    tablesCount: 0,
    ordersCount: 42,
    rating: 4.9,
    phone: '+1 (555) 678-9012',
    email: 'marco.b@restaurant.com',
    hourlyRate: 26.0,
    startDate: '2023-05-01',
    emergencyContact: '+1 (555) 543-2109',
  },
  {
    id: 'staff-6',
    firstName: 'Elena',
    lastName: 'Rostova',
    fullName: 'Elena Rostova',
    initials: 'ER',
    role: 'Chef',
    status: 'Active',
    shift: '8AM – 4PM',
    tablesCount: 0,
    ordersCount: 28,
    rating: 4.8,
    phone: '+1 (555) 789-0123',
    email: 'elena.r@restaurant.com',
    hourlyRate: 24.0,
    startDate: '2023-08-15',
    emergencyContact: '+1 (555) 432-1098',
  },
  {
    id: 'staff-7',
    firstName: 'Marcus',
    lastName: 'Brody',
    fullName: 'Marcus Brody',
    initials: 'MB',
    role: 'Bartender',
    status: 'Active',
    shift: '11AM – 7PM',
    tablesCount: 0,
    ordersCount: 36,
    rating: 4.8,
    phone: '+1 (555) 890-1234',
    email: 'marcus.b@restaurant.com',
    hourlyRate: 21.0,
    startDate: '2024-02-01',
    emergencyContact: '+1 (555) 321-0987',
  },
  {
    id: 'staff-8',
    firstName: 'Sarah',
    lastName: 'Johnson',
    fullName: 'Sarah Johnson',
    initials: 'SJ',
    role: 'Manager',
    status: 'Active',
    shift: '8AM – 5PM',
    tablesCount: 0,
    ordersCount: 0,
    rating: 5.0,
    phone: '+1 (555) 901-2345',
    email: 'manager@tavonza.com',
    hourlyRate: 32.0,
    startDate: '2022-09-01',
    emergencyContact: '+1 (555) 210-9876',
  },
  {
    id: 'staff-9',
    firstName: 'Carlos',
    lastName: 'Gomez',
    fullName: 'Carlos Gomez',
    initials: 'CG',
    role: 'Waiter',
    status: 'On Break',
    shift: '8AM – 4PM',
    tablesCount: 2,
    ordersCount: 11,
    rating: 4.6,
    phone: '+1 (555) 012-3456',
    email: 'carlos.g@restaurant.com',
    hourlyRate: 17.0,
    startDate: '2024-05-10',
    emergencyContact: '+1 (555) 109-8765',
  },
  {
    id: 'staff-10',
    firstName: 'Aria',
    lastName: 'Tanaka',
    fullName: 'Aria Tanaka',
    initials: 'AT',
    role: 'Waiter',
    status: 'On Break',
    shift: '12PM – 8PM',
    tablesCount: 2,
    ordersCount: 9,
    rating: 4.8,
    phone: '+1 (555) 123-4567',
    email: 'aria.t@restaurant.com',
    hourlyRate: 18.0,
    startDate: '2024-06-01',
    emergencyContact: '+1 (555) 098-7654',
  },
  {
    id: 'staff-11',
    firstName: 'Leo',
    lastName: 'Martinez',
    fullName: 'Leo Martinez',
    initials: 'LM',
    role: 'Busser',
    status: 'Active',
    shift: '10AM – 6PM',
    tablesCount: 0,
    ordersCount: 24,
    rating: 4.7,
    phone: '+1 (555) 234-5670',
    email: 'leo.m@restaurant.com',
    hourlyRate: 15.5,
    startDate: '2024-06-15',
    emergencyContact: '+1 (555) 987-6540',
  },
  {
    id: 'staff-12',
    firstName: 'Chloe',
    lastName: 'Bennett',
    fullName: 'Chloe Bennett',
    initials: 'CB',
    role: 'Host',
    status: 'Active',
    shift: '8AM – 4PM',
    tablesCount: 0,
    ordersCount: 0,
    rating: 4.9,
    phone: '+1 (555) 345-6781',
    email: 'chloe.b@restaurant.com',
    hourlyRate: 16.5,
    startDate: '2024-04-20',
    emergencyContact: '+1 (555) 876-5431',
  },
];

// ==========================================
// Customer Management Initial Mock Data
// ==========================================
export const initialCustomerKPIs: CustomerKPIsData = {
  totalCustomers: 1284,
  totalCustomersSubtitle: '↑ 42 new this month',
  vipMembers: 186,
  vipSubtitle: 'Top spenders',
  avgRating: 4.8,
  avgRatingSubtitle: 'From 312 reviews',
  returnRate: 68,
  returnRateSubtitle: 'Repeat visitors',
};

export const initialCustomers: ManagerCustomer[] = [
  {
    id: 'cust-1',
    firstName: 'Alexandra',
    lastName: 'Turner',
    name: 'Alexandra Turner',
    initials: 'AT',
    phone: '+1 (555) 000-0000',
    email: 'alex@email.com',
    dob: '1992-04-14',
    preferredTable: 'T-05 (window side)',
    dietaryPreferences: 'Vegetarian, nut allergy',
    notes: 'Favourite dish: Truffle Pasta. Anniversary on Oct 14.',
    isVIP: true,
    rating: 5,
    visits: 24,
    spent: 1240,
    lastVisit: 'Today',
  },
  {
    id: 'cust-2',
    firstName: 'David',
    lastName: 'Chen',
    name: 'David Chen',
    initials: 'DC',
    phone: '+1 (555) 234-5678',
    email: 'david.c@example.com',
    dob: '1988-09-21',
    preferredTable: 'T-02 (booth)',
    dietaryPreferences: 'Gluten-free',
    notes: 'Likes corner booth, prefers sparkling water.',
    isVIP: true,
    rating: 5,
    visits: 31,
    spent: 1890,
    lastVisit: 'Yesterday',
  },
  {
    id: 'cust-3',
    firstName: 'Sophia',
    lastName: 'Martinez',
    name: 'Sophia Martinez',
    initials: 'SM',
    phone: '+1 (555) 345-6789',
    email: 'sophia.m@example.com',
    dob: '1995-12-03',
    preferredTable: 'T-08 (patio)',
    dietaryPreferences: 'Dairy-free',
    notes: 'Wine enthusiast, always orders Pinot Noir.',
    isVIP: true,
    rating: 5,
    visits: 19,
    spent: 950,
    lastVisit: '2 days ago',
  },
  {
    id: 'cust-4',
    firstName: 'Michael',
    lastName: 'Brown',
    name: 'Michael Brown',
    initials: 'MB',
    phone: '+1 (555) 456-7890',
    email: 'michael.b@example.com',
    dob: '1985-06-18',
    preferredTable: 'T-03',
    dietaryPreferences: 'None',
    notes: 'Frequent business lunch guest.',
    isVIP: false,
    rating: 4,
    visits: 12,
    spent: 560,
    lastVisit: '3 days ago',
  },
  {
    id: 'cust-5',
    firstName: 'Emily',
    lastName: 'Watson',
    name: 'Emily Watson',
    initials: 'EW',
    phone: '+1 (555) 567-8901',
    email: 'emily.w@example.com',
    dob: '1991-03-29',
    preferredTable: 'T-05',
    dietaryPreferences: 'Shellfish allergy',
    notes: 'Loves chocolate lava cake.',
    isVIP: true,
    rating: 5,
    visits: 28,
    spent: 1420,
    lastVisit: 'May 12',
  },
  {
    id: 'cust-6',
    firstName: 'James',
    lastName: 'Wilson',
    name: 'James Wilson',
    initials: 'JW',
    phone: '+1 (555) 678-9012',
    email: 'james.w@example.com',
    dob: '1989-11-05',
    preferredTable: 'T-07',
    dietaryPreferences: 'None',
    notes: 'Regular Friday evening dinner guest.',
    isVIP: false,
    rating: 5,
    visits: 15,
    spent: 780,
    lastVisit: 'May 10',
  },
  {
    id: 'cust-7',
    firstName: 'Lucas',
    lastName: 'Vance',
    name: 'Lucas Vance',
    initials: 'LV',
    phone: '+1 (555) 789-0123',
    email: 'lucas.v@example.com',
    dob: '1980-01-15',
    preferredTable: 'T-01 (VIP Room)',
    dietaryPreferences: 'Low sodium',
    notes: 'Entertains corporate executive clients.',
    isVIP: true,
    rating: 5,
    visits: 42,
    spent: 2450,
    lastVisit: 'May 08',
  },
  {
    id: 'cust-8',
    firstName: 'Isabella',
    lastName: 'Garcia',
    name: 'Isabella Garcia',
    initials: 'IG',
    phone: '+1 (555) 890-1234',
    email: 'isabella.g@example.com',
    dob: '1996-07-22',
    preferredTable: 'T-04',
    dietaryPreferences: 'Vegan',
    notes: 'Loves plant-based chef specials.',
    isVIP: false,
    rating: 4,
    visits: 8,
    spent: 390,
    lastVisit: 'May 05',
  },
  {
    id: 'cust-9',
    firstName: 'Liam',
    lastName: 'Davis',
    name: 'Liam Davis',
    initials: 'LD',
    phone: '+1 (555) 901-2345',
    email: 'liam.d@example.com',
    dob: '1993-08-30',
    preferredTable: 'T-06',
    dietaryPreferences: 'Nut allergy',
    notes: 'Orders extra espresso with dessert.',
    isVIP: false,
    rating: 5,
    visits: 11,
    spent: 620,
    lastVisit: 'May 02',
  },
];

// ==========================================
// Analytics & Reports Initial Data
// ==========================================
export const initialAnalyticsKPIs: import('./types').AnalyticsKPIData = {
  revenueToday: '$8,420',
  revenueTrend: '↑ 12% vs yesterday',
  ordersToday: 132,
  ordersTrend: '↑ 8% vs yesterday',
  avgOrderValue: '$32.40',
  avgOrderTrend: '↑ $2.10 vs yesterday',
  tableTurnover: '3.2x',
  turnoverSubtitle: 'Per table today',
};

export const timeframeAnalyticsKPIs: Record<import('./types').AnalyticsTimeframe, import('./types').AnalyticsKPIData> = {
  Today: {
    revenueToday: '$4,850',
    revenueTrend: '↑ 6% vs yesterday',
    ordersToday: 84,
    ordersTrend: '↑ 4% vs yesterday',
    avgOrderValue: '$31.80',
    avgOrderTrend: '↑ $1.40 vs yesterday',
    tableTurnover: '2.4x',
    turnoverSubtitle: 'Per table today',
  },
  'This Week': {
    revenueToday: '$8,420',
    revenueTrend: '↑ 12% vs yesterday',
    ordersToday: 132,
    ordersTrend: '↑ 8% vs yesterday',
    avgOrderValue: '$32.40',
    avgOrderTrend: '↑ $2.10 vs yesterday',
    tableTurnover: '3.2x',
    turnoverSubtitle: 'Per table today',
  },
  'This Month': {
    revenueToday: '$36,890',
    revenueTrend: '↑ 18% vs last month',
    ordersToday: 540,
    ordersTrend: '↑ 14% vs last month',
    avgOrderValue: '$34.20',
    avgOrderTrend: '↑ $3.50 vs last month',
    tableTurnover: '3.5x',
    turnoverSubtitle: 'Daily average turnover',
  },
  'This Quarter': {
    revenueToday: '$118,450',
    revenueTrend: '↑ 22% vs last quarter',
    ordersToday: 1820,
    ordersTrend: '↑ 19% vs last quarter',
    avgOrderValue: '$35.10',
    avgOrderTrend: '↑ $4.10 vs last quarter',
    tableTurnover: '3.7x',
    turnoverSubtitle: 'Quarterly average turnover',
  },
};

export const initialTrafficData: import('./types').TrafficDataPoint[] = [
  { day: 'Mon', value: 2950, dineIn: 2100, takeout: 850 },
  { day: 'Tue', value: 3400, dineIn: 2450, takeout: 950 },
  { day: 'Wed', value: 4050, dineIn: 2850, takeout: 1200 },
  { day: 'Thus', value: 2950, dineIn: 2100, takeout: 850 },
  { day: 'Friday', value: 4900, dineIn: 3500, takeout: 1400 },
  { day: 'Sat', value: 6950, dineIn: 5150, takeout: 1800 },
  { day: 'Sun', value: 3700, dineIn: 2700, takeout: 1000 },
];

export const initialCategoryRevenue: import('./types').CategoryRevenuePoint[] = [
  { name: 'Mains', percentage: 38, color: '#F97316', amount: 3200, amountFormatted: '$3,200 (38%)' },
  { name: 'Pizza', percentage: 22, color: '#3B82F6', amount: 1852, amountFormatted: '$1,852 (22%)' },
  { name: 'Burgers', percentage: 18, color: '#A855F7', amount: 1515, amountFormatted: '$1,515 (18%)' },
  { name: 'Beverages', percentage: 12, color: '#22C55E', amount: 1010, amountFormatted: '$1,010 (12%)' },
  { name: 'Desserts', percentage: 10, color: '#EC4899', amount: 843, amountFormatted: '$843 (10%)' },
];

export const initialCategoryBreakdown: import('./types').CategoryBreakdownRow[] = [
  { id: 'cat-1', category: 'Mains', itemsSold: 142, grossRevenue: 3200, avgTicket: 22.54, share: 38, growth: '+14%' },
  { id: 'cat-2', category: 'Pizza', itemsSold: 98, grossRevenue: 1852, avgTicket: 18.90, share: 22, growth: '+8%' },
  { id: 'cat-3', category: 'Burgers', itemsSold: 86, grossRevenue: 1515, avgTicket: 17.62, share: 18, growth: '+11%' },
  { id: 'cat-4', category: 'Beverages', itemsSold: 165, grossRevenue: 1010, avgTicket: 6.12, share: 12, growth: '+5%' },
  { id: 'cat-5', category: 'Desserts', itemsSold: 74, grossRevenue: 843, avgTicket: 11.39, share: 10, growth: '+19%' },
];

// ==========================================
// AI Insights Initial Data
// ==========================================
export const initialAIInsightsKPIs: import('./types').AIInsightsKPIData = {
  insightsGenerated: 24,
  insightsGeneratedSubtitle: 'In last 24 hours',
  actionsSuggested: 8,
  actionsSuggestedSubtitle: '3 high priority',
  accuracyRate: '94%',
  accuracyRateSubtitle: 'Of past predictions',
  efficiencyGain: '+11%',
  efficiencyGainSubtitle: 'From AI actions',
};

export const initialAIInsightItems: import('./types').AIInsightItem[] = [
  {
    id: 'ai-1',
    title: 'Revenue Forecast',
    badgeText: 'positive',
    badgeType: 'positive',
    description: "Today's revenue is projected to reach $5,200 — 21% above weekly average. Dinner service expected to peak at 7:30 PM.",
    actionText: 'Take Action',
    iconType: 'revenue',
    impactMetric: '+$900 projected revenue',
    recommendedAction: 'Extend dining bar staffing and prep extra dinner mis-en-place for 7:00 PM - 9:00 PM wave.',
    status: 'pending',
  },
  {
    id: 'ai-2',
    title: 'Staffing Optimization',
    badgeText: 'Action',
    badgeType: 'action',
    description: 'Reassigning one waiter from Floor 1 to Floor 2 between 12–2 PM could reduce average wait time by 4 minutes.',
    actionText: 'Take Action',
    iconType: 'staffing',
    impactMetric: '-4 mins table wait time',
    recommendedAction: 'Shift Waiter Lucas Vance to Floor 2 section during lunch rush hour.',
    status: 'pending',
  },
  {
    id: 'ai-3',
    title: 'Menu Performance',
    badgeText: 'insight',
    badgeType: 'insight',
    description: 'Ribeye Steak has 94% order completion. Chocolate Lava Cake upsell rate is 12% higher when suggested at checkout.',
    actionText: 'Take Action',
    iconType: 'menu',
    impactMetric: '+12% dessert up-sell rate',
    recommendedAction: 'Enable automated POS prompt suggesting Chocolate Lava Cake pairing for steak orders.',
    status: 'pending',
  },
  {
    id: 'ai-4',
    title: 'Inventory Risk',
    badgeText: 'warning',
    badgeType: 'warning',
    description: 'At current usage rates, mozzarella cheese will run out by 5:30 PM. Red wine stock will deplete within 2 days.',
    actionText: 'Take Action',
    iconType: 'inventory',
    impactMetric: 'Low stock threshold alert',
    recommendedAction: 'Trigger emergency 5kg mozzarella replenishment order from local dairy supplier.',
    status: 'pending',
  },
  {
    id: 'ai-5',
    title: 'Customer Loyalty',
    badgeText: 'insight',
    badgeType: 'insight',
    description: '3 VIP customers are dining today. Alexandra Turner has not received a loyalty reward in 8 visits — an offer could improve retention.',
    actionText: 'Take Action',
    iconType: 'loyalty',
    impactMetric: '+18% VIP retention boost',
    recommendedAction: 'Send complimentary glass of vintage wine voucher to Table T-01 for Alexandra Turner.',
    status: 'pending',
  },
  {
    id: 'ai-6',
    title: 'Kitchen Efficiency',
    badgeText: 'Action',
    badgeType: 'action',
    description: 'Grill station handled 38% of all orders. Shifting 2 burger orders to fry station would reduce ticket time from 13 to 10 minutes.',
    actionText: 'Take Action',
    iconType: 'kitchen',
    impactMetric: '-3 mins kitchen ticket time',
    recommendedAction: 'Reroute Smash Burger prep ticket routing rule to Station 2 (Fry / Sauté).',
    status: 'pending',
  },
];

// ==========================================
// Manager Notifications Initial Data
// ==========================================
export const initialManagerNotifications: import('./types').ManagerNotificationItem[] = [
  {
    id: 'notif-1',
    title: 'Table 12 waiting 18+ minutes',
    description: 'Customer at Table 12 has been waiting for 18 minutes without service.',
    timestamp: '2 min ago',
    isUnread: true,
    isNew: true,
    severity: 'urgent',
    category: 'table',
  },
  {
    id: 'notif-2',
    title: 'Kitchen prep time increased',
    description: 'Average kitchen preparation time has increased by 9% in the last 30 minutes.',
    timestamp: '5 min ago',
    isUnread: true,
    isNew: true,
    severity: 'warning',
    category: 'kitchen',
  },
  {
    id: 'notif-3',
    title: 'Low stock: Soft Drinks',
    description: 'Soft drinks inventory has dropped below the minimum threshold (18 cans remaining).',
    timestamp: '12 min ago',
    isUnread: true,
    isNew: true,
    severity: 'caution',
    category: 'inventory',
  },
  {
    id: 'notif-4',
    title: 'VIP customer checked in',
    description: 'Alexandra Turner (24 visits, $1,240 total spend) has been seated at Table 05.',
    timestamp: '25 min ago',
    isUnread: false,
    isNew: false,
    severity: 'info',
    category: 'customer',
  },
  {
    id: 'notif-5',
    title: 'Noah Davis started break',
    description: 'Noah Davis (Waiter) has started his scheduled 30-minute break.',
    timestamp: '45 min ago',
    isUnread: false,
    isNew: false,
    severity: 'info',
    category: 'staff',
  },
  {
    id: 'notif-6',
    title: 'Order #10519 marked complete',
    description: 'Order for Table 04 completed successfully. Total: $84.50.',
    timestamp: '1 hour ago',
    isUnread: false,
    isNew: false,
    severity: 'info',
    category: 'order',
  },
  {
    id: 'notif-7',
    title: 'Low stock: Mozzarella Cheese',
    description: 'Mozzarella cheese is critically low (2.4kg remaining). Reorder recommended before dinner.',
    timestamp: '2 hours ago',
    isUnread: false,
    isNew: false,
    severity: 'info',
    category: 'inventory',
  },
  {
    id: 'notif-8',
    title: 'Daily lunch report available',
    description: 'Lunch service summary is ready. 132 orders, $4,280 revenue, 94% satisfaction.',
    timestamp: '3 hours ago',
    isUnread: false,
    isNew: false,
    severity: 'info',
    category: 'report',
  },
];

// ==========================================
// Manager Settings Initial Data
// ==========================================
export const initialRestaurantInfo: import('./types').RestaurantInfoSettings = {
  restaurantName: 'Tavonza Downtown',
  branch: 'Downtown Branch',
  address: '123 Main Street, New York, NY',
  phone: '+1 (212) 555-0192',
};

export const initialNotificationToggles: import('./types').NotificationSettingToggle[] = [
  { id: 'notif-tog-1', label: 'Delayed order alerts', enabled: true },
  { id: 'notif-tog-2', label: 'Low inventory alerts', enabled: true },
  { id: 'notif-tog-3', label: 'Staff check-in', enabled: false },
  { id: 'notif-tog-4', label: 'Customer feedback', enabled: true },
  { id: 'notif-tog-5', label: 'Daily report', enabled: true },
];

export const initialAIOperationToggles: import('./types').AIOperationSettingToggle[] = [
  { id: 'ai-tog-1', label: 'AI order suggestions', enabled: true },
  { id: 'ai-tog-2', label: 'Automatic alerts', enabled: true },
  { id: 'ai-tog-3', label: 'Kitchen auto-bump', enabled: false },
  { id: 'ai-tog-4', label: 'VIP auto-notifications', enabled: true },
  { id: 'ai-tog-5', label: 'Demand forecasting', enabled: true },
];

export const initialIntegrations: import('./types').IntegrationSettingItem[] = [
  { id: 'integ-1', name: 'POS System', status: 'Connected', category: 'Point of Sale' },
  { id: 'integ-2', name: 'Payment Gateway', status: 'Connected', category: 'Payments' },
  { id: 'integ-3', name: 'Delivery Platform', status: 'Disconnected', category: 'Third-party Logistics' },
  { id: 'integ-4', name: 'Accounting', status: 'Connected', category: 'ERP & Bookkeeping' },
];

