import {
  FloorOccupancyKPI,
  SeatedGuestsKPI,
  StaffActiveKPI,
  FrontlineAlertsKPI,
  QuickActionCard,
  FloorTable,
  ShiftNoteData,
  FrontlineAlert,
  OutOfStockItem,
  StaffMember,
  EscalationTicket,
} from './types';

export const mockFloorOccupancy: FloorOccupancyKPI = {
  rate: '67%',
  tablesFraction: '(16/24 tables)',
  tablesOpen: 4,
  bussingCount: 2,
};

export const mockSeatedGuests: SeatedGuestsKPI = {
  totalGuests: 55,
  unit: 'covers',
  subtitle: 'Dining across floor',
  waitlistCount: 8,
};

export const mockStaffActive: StaffActiveKPI = {
  activeCount: '08',
  rosteredTotal: '/10 rostered',
  coverageNote: 'All 4 zones covered',
};

export const mockFrontlineAlertsKPI: FrontlineAlertsKPI = {
  pendingCount: '06',
  statusLabel: 'pending review',
  actionNote: 'Requires AM action',
  actionLabel: 'Snapshot',
};

export const mockQuickActions: QuickActionCard[] = [
  {
    id: '86-stock',
    title: "86'd Stock",
    subtitle: 'Live items & pos sync',
    actionText: 'Manage',
    actionType: 'manage',
    isHighlighted: true,
  },
  {
    id: 'shift-handoff',
    title: 'Shift Handoff',
    subtitle: 'Manager log & report',
    actionText: 'Review',
    actionType: 'review',
  },
  {
    id: 'shift-note',
    title: 'Shift Note',
    subtitle: 'Floor broadcast',
    actionText: 'Send',
    actionType: 'send',
  },
  {
    id: 'elena-vance',
    title: 'Elena Vance',
    subtitle: 'Restaurant Manager',
    actionText: '',
    actionType: 'status',
    statusBadge: 'on-site',
  },
];

export const mockShiftNote: ShiftNoteData = {
  id: 'sn-01',
  title: 'Shift Note',
  content:
    'VIP corporate guests seated at Table 04 (Apex Capital) & PR-1. Please prioritize beverage check-backs and keep course timing strictly under 15m between plates.',
  author: 'Marcus Vance',
  role: 'Assistant Manager',
  timestamp: '10:15 AM',
  priority: 'high',
  targetZones: ['Main Dining', 'Private Room'],
};

export const mockFloorTables: FloorTable[] = [
  {
    id: 't-02-a',
    tableNumber: 'Table- 02',
    zone: 'Main Dining',
    capacity: 4,
    currentGuests: 4,
    status: 'Dining',
    totalAmount: '$78.00',
    course: 'Course : Just Seated',
    itemsCount: 1,
    elapsedMinutes: 8,
    targetMinutes: 60,
    serverName: 'Maya Patel',
    orderItems: [
      { id: 'oi-1', name: 'Truffle Mushroom Risotto', quantity: 1, price: '$34.00', status: 'preparing' },
      { id: 'oi-2', name: 'Wagyu Beef Sliders', quantity: 1, price: '$26.00', status: 'preparing' },
      { id: 'oi-3', name: 'Sparkling Mineral Water', quantity: 2, price: '$18.00', status: 'served' },
    ],
  },
  {
    id: 't-04-a',
    tableNumber: 'Table- 04',
    zone: 'Main Dining',
    capacity: 4,
    currentGuests: 4,
    status: 'Dining',
    totalAmount: '$142.50',
    course: 'Course : Mains In Progress',
    itemsCount: 3,
    elapsedMinutes: 24,
    targetMinutes: 60,
    serverName: 'Maya Patel',
    orderItems: [
      { id: 'oi-4', name: 'Pan-Seared Sea Bass', quantity: 2, price: '$68.00', status: 'preparing' },
      { id: 'oi-5', name: 'Ribeye Steak (Medium)', quantity: 1, price: '$54.00', status: 'preparing' },
      { id: 'oi-6', name: 'Cabernet Sauvignon Bottle', quantity: 1, price: '$65.00', status: 'served' },
    ],
  },
  {
    id: 't-01-a',
    tableNumber: 'Table- 01',
    zone: 'Main Dining',
    capacity: 2,
    currentGuests: 2,
    status: 'Attention',
    totalAmount: '$78.00',
    alertMessage: 'Kitchen delay on mains (18m behind ticket)',
    course: 'Course : Just Seated',
    itemsCount: 1,
    elapsedMinutes: 8,
    targetMinutes: 60,
    serverName: 'Maya Patel',
    orderItems: [
      { id: 'oi-7', name: 'Dry-Aged Tomahawk Rib', quantity: 1, price: '$78.00', status: 'delayed' },
    ],
  },
  {
    id: 't-03-a',
    tableNumber: 'Table- 03',
    zone: 'Main Dining',
    capacity: 4,
    currentGuests: 4,
    status: 'Dining',
    totalAmount: '$96.00',
    course: 'Course : Appetizers Served',
    itemsCount: 2,
    elapsedMinutes: 14,
    targetMinutes: 60,
    serverName: 'Maya Patel',
    orderItems: [
      { id: 'oi-8', name: 'Crispy Calamari', quantity: 2, price: '$36.00', status: 'served' },
      { id: 'oi-9', name: 'Grilled Mediterranean Salmon', quantity: 2, price: '$60.00', status: 'preparing' },
    ],
  },
  {
    id: 't-02-b',
    tableNumber: 'Table- 02',
    zone: 'Main Dining',
    capacity: 4,
    currentGuests: 0,
    status: 'Bussing',
    awaitingReset: true,
    serverName: 'Maya Patel',
  },
  {
    id: 't-05-a',
    tableNumber: 'Table- 05',
    zone: 'Main Dining',
    capacity: 4,
    currentGuests: 4,
    status: 'Dining',
    totalAmount: '$78.00',
    course: 'Course : Just Seated',
    itemsCount: 1,
    elapsedMinutes: 8,
    targetMinutes: 60,
    serverName: 'Maya Patel',
    orderItems: [
      { id: 'oi-10', name: 'Roasted Duck Breast', quantity: 2, price: '$78.00', status: 'preparing' },
    ],
  },
  {
    id: 't-06-a',
    tableNumber: 'Table- 06',
    zone: 'Main Dining',
    capacity: 4,
    currentGuests: 4,
    status: 'Dining',
    totalAmount: '$78.00',
    course: 'Course : Just Seated',
    itemsCount: 1,
    elapsedMinutes: 8,
    targetMinutes: 60,
    serverName: 'Maya Patel',
    orderItems: [
      { id: 'oi-11', name: 'Handmade Gnocchi Pesto', quantity: 2, price: '$54.00', status: 'preparing' },
      { id: 'oi-12', name: 'Prosecco Glass', quantity: 2, price: '$24.00', status: 'served' },
    ],
  },
  {
    id: 't-07-a',
    tableNumber: 'Table- 07',
    zone: 'Main Dining',
    capacity: 2,
    currentGuests: 2,
    status: 'Attention',
    totalAmount: '$78.00',
    alertMessage: 'Kitchen delay on mains (18m behind ticket)',
    course: 'Course : Just Seated',
    itemsCount: 1,
    elapsedMinutes: 8,
    targetMinutes: 60,
    serverName: 'Maya Patel',
    orderItems: [
      { id: 'oi-13', name: 'Lobster Ravioli', quantity: 2, price: '$78.00', status: 'delayed' },
    ],
  },
  // Additional zone tables for seamless filtering
  {
    id: 't-p-01',
    tableNumber: 'Table- P1',
    zone: 'Patio',
    capacity: 4,
    currentGuests: 3,
    status: 'Dining',
    totalAmount: '$112.00',
    course: 'Course : Entrees Served',
    itemsCount: 4,
    elapsedMinutes: 32,
    targetMinutes: 60,
    serverName: 'Liam Carter',
  },
  {
    id: 't-p-02',
    tableNumber: 'Table- P2',
    zone: 'Patio',
    capacity: 2,
    currentGuests: 0,
    status: 'Ready',
    serverName: 'Liam Carter',
  },
  {
    id: 't-b-01',
    tableNumber: 'Bar- Top 01',
    zone: 'Bar & High Tops',
    capacity: 2,
    currentGuests: 2,
    status: 'Dining',
    totalAmount: '$54.00',
    course: 'Course : Cocktails & Bites',
    itemsCount: 3,
    elapsedMinutes: 15,
    targetMinutes: 45,
    serverName: 'Chloe Bennett',
  },
  {
    id: 't-b-02',
    tableNumber: 'Bar- Top 02',
    zone: 'Bar & High Tops',
    capacity: 2,
    currentGuests: 1,
    status: 'Check Out',
    totalAmount: '$38.50',
    course: 'Course : Settling Bill',
    itemsCount: 2,
    elapsedMinutes: 42,
    targetMinutes: 45,
    serverName: 'Chloe Bennett',
  },
  {
    id: 't-pr-01',
    tableNumber: 'PR-1 (Executive)',
    zone: 'Private Room',
    capacity: 12,
    currentGuests: 10,
    status: 'Dining',
    totalAmount: '$485.00',
    course: 'Course : Tasting Menu Phase 2',
    itemsCount: 8,
    elapsedMinutes: 55,
    targetMinutes: 120,
    serverName: 'Julian Vance',
  },
];

export const mockFrontlineAlerts: FrontlineAlert[] = [
  {
    id: 'alert-01',
    tableNumber: 'Table- 01',
    zone: 'Main Dining',
    title: 'Kitchen Delay on Mains',
    description: 'Ticket #1042 running 18 minutes past target prep threshold.',
    elapsedMinutes: 18,
    severity: 'critical',
    server: 'Maya Patel',
    timestamp: '10:18 AM',
  },
  {
    id: 'alert-02',
    tableNumber: 'Table- 07',
    zone: 'Main Dining',
    title: 'Kitchen Delay on Mains',
    description: 'Ticket #1048 lobster ravioli prep bottleneck.',
    elapsedMinutes: 18,
    severity: 'critical',
    server: 'Maya Patel',
    timestamp: '10:14 AM',
  },
  {
    id: 'alert-03',
    tableNumber: 'Table- 02',
    zone: 'Main Dining',
    title: 'Bussing Turnaround Awaiting',
    description: 'Table cleared 7 minutes ago, requires sanitization and reset.',
    elapsedMinutes: 7,
    severity: 'warning',
    server: 'Maya Patel',
    timestamp: '10:13 AM',
  },
  {
    id: 'alert-04',
    tableNumber: 'Table- P1',
    zone: 'Patio',
    title: 'Drink Check-Back Prompt',
    description: 'Cocktail refilled 20 minutes ago. Guest flagged server.',
    elapsedMinutes: 12,
    severity: 'warning',
    server: 'Liam Carter',
    timestamp: '10:10 AM',
  },
  {
    id: 'alert-05',
    tableNumber: 'PR-1',
    zone: 'Private Room',
    title: 'VIP Beverage Priority',
    description: 'Apex Capital hosting meeting, requested vintage decanter.',
    elapsedMinutes: 5,
    severity: 'info',
    server: 'Julian Vance',
    timestamp: '10:05 AM',
  },
  {
    id: 'alert-06',
    tableNumber: 'Bar- Top 02',
    zone: 'Bar & High Tops',
    title: 'Split Check Request',
    description: 'Guest requested handheld mobile checkout terminal.',
    elapsedMinutes: 4,
    severity: 'info',
    server: 'Chloe Bennett',
    timestamp: '10:02 AM',
  },
];

export const mockOutOfStockItems: OutOfStockItem[] = [
  {
    id: 'oos-1',
    name: 'Wild Alaskan Halibut',
    category: 'Kitchen',
    posStatus: '86ed',
    reportedBy: 'Chef Marco',
    reportedTime: '09:45 AM',
  },
  {
    id: 'oos-2',
    name: 'Vintage 2018 Barolo',
    category: 'Bar',
    posStatus: '86ed',
    reportedBy: 'Elena Vance (RM)',
    reportedTime: '10:00 AM',
  },
  {
    id: 'oos-3',
    name: 'Valrhona Chocolate Soufflé',
    category: 'Dessert',
    posStatus: 'low_stock',
    reportedBy: 'Pastry Chef Sarah',
    reportedTime: '10:12 AM',
  },
];

export const mockStaffRoster: StaffMember[] = [
  {
    id: 'st-01',
    name: 'Maya Patel',
    role: 'Lead Server',
    zone: 'Main Dining',
    activeTables: 4,
    status: 'active',
    shiftHours: '08:00 AM - 04:00 PM',
    avatar: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'st-02',
    name: 'Liam Carter',
    role: 'Server',
    zone: 'Patio',
    activeTables: 2,
    status: 'active',
    shiftHours: '09:00 AM - 05:00 PM',
    avatar: 'https://images.unsplash.com/photo-1534528741775-53994a69daeb?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'st-03',
    name: 'Chloe Bennett',
    role: 'Head Bartender',
    zone: 'Bar & High Tops',
    activeTables: 3,
    status: 'active',
    shiftHours: '10:00 AM - 06:00 PM',
    avatar: 'https://images.unsplash.com/photo-1580489944761-15a19d654956?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'st-04',
    name: 'Julian Vance',
    role: 'VIP Concierge Server',
    zone: 'Private Room',
    activeTables: 1,
    status: 'active',
    shiftHours: '09:30 AM - 05:30 PM',
    avatar: 'https://images.unsplash.com/photo-1507003211169-0a1dd7228f2d?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'st-05',
    name: 'David Chen',
    role: 'Expediter',
    zone: 'Kitchen Pass',
    activeTables: 0,
    status: 'active',
    shiftHours: '08:30 AM - 04:30 PM',
    avatar: 'https://images.unsplash.com/photo-1500648767791-00dcc994a43e?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'st-06',
    name: 'Sofia Rodriguez',
    role: 'Floor Busser',
    zone: 'Main Dining / Patio',
    activeTables: 0,
    status: 'active',
    shiftHours: '09:00 AM - 05:00 PM',
    avatar: 'https://images.unsplash.com/photo-1544005313-94ddf0286df2?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'st-07',
    name: 'Marcus Vance',
    role: 'Assistant Manager',
    zone: 'Floor Control',
    activeTables: 0,
    status: 'active',
    shiftHours: '07:30 AM - 04:00 PM',
    avatar: 'https://images.unsplash.com/photo-1539571696357-5a69c17a67c6?w=150&auto=format&fit=crop&q=80',
  },
  {
    id: 'st-08',
    name: 'Elena Vance',
    role: 'Restaurant Manager',
    zone: 'All Operations',
    activeTables: 0,
    status: 'active',
    shiftHours: '09:00 AM - 06:00 PM',
    avatar: 'https://images.unsplash.com/photo-1567532939604-b6b5b0db2604?w=150&auto=format&fit=crop&q=80',
  },
];

export const mockEscalationTickets: EscalationTicket[] = [
  {
    id: 'esc-01',
    sourceType: 'Waiter',
    timeAgo: '3m ago',
    title: 'Comp Request: $18.00 (T-14)',
    description:
      'Server Emma Watson requested $18.00 comp for Table 14 (Torta Della Nonna x2) due to 20min kitchen backlog on dessert pass.',
    flaggedBy: 'Emma Watson (Server)',
    amount: '$18.00',
    tableNumber: 'Table 14',
    zone: 'Main Dining',
    department: 'Waiters',
    status: 'Pending Action',
    canApproveDirectly: true,
  },
  {
    id: 'esc-02',
    sourceType: 'Kitchen',
    timeAgo: '3m ago',
    title: 'Comp Request: $18.00 (T-14)',
    description:
      'Server Emma Watson requested $18.00 comp for Table 14 (Torta Della Nonna x2) due to 20min kitchen backlog on dessert pass.',
    flaggedBy: 'KDS System (Auto-Trigger)',
    amount: '$18.00',
    tableNumber: 'Table 14',
    zone: 'Main Dining',
    department: 'Kitchen & KDS',
    status: 'Pending Action',
    canApproveDirectly: false,
  },
  {
    id: 'esc-03',
    sourceType: 'Cashier',
    timeAgo: '3m ago',
    title: 'Comp Request: $18.00 (T-14)',
    description:
      'Server Emma Watson requested $18.00 comp for Table 14 (Torta Della Nonna x2) due to 20min kitchen backlog on dessert pass.',
    flaggedBy: 'KDS System (Auto-Trigger)',
    amount: '$18.00',
    tableNumber: 'Table 14',
    zone: 'Main Dining',
    department: 'Cashier',
    status: 'Pending Action',
    canApproveDirectly: false,
  },
  {
    id: 'esc-04',
    sourceType: 'Host',
    timeAgo: '3m ago',
    title: 'Comp Request: $18.00 (T-14)',
    description:
      'Server Emma Watson requested $18.00 comp for Table 14 (Torta Della Nonna x2) due to 20min kitchen backlog on dessert pass.',
    flaggedBy: 'KDS System (Auto-Trigger)',
    amount: '$18.00',
    tableNumber: 'Table 14',
    zone: 'Main Dining',
    department: 'Host',
    status: 'Pending Action',
    canApproveDirectly: false,
  },
  {
    id: 'esc-05',
    sourceType: 'Waiter',
    timeAgo: '8m ago',
    title: 'VIP Beverage Check-Back Escalation (PR-1)',
    description:
      'Apex Capital guests requested vintage decanter refill and wine service check-back.',
    flaggedBy: 'Julian Vance (Concierge Server)',
    amount: '$65.00',
    tableNumber: 'PR-1',
    zone: 'Private Room',
    department: 'Waiters',
    status: 'Forwarded to RM',
    canApproveDirectly: true,
  },
  {
    id: 'esc-06',
    sourceType: 'Ready',
    timeAgo: '15m ago',
    title: 'Table 02 Sanitize Reset Completed',
    description:
      'Bussing turnaround completed in 6m. Ready for host seating queue (+8 waitlist).',
    flaggedBy: 'Sofia Rodriguez (Floor Busser)',
    tableNumber: 'Table 02',
    zone: 'Main Dining',
    department: 'Ready',
    status: 'Resolved',
    canApproveDirectly: false,
  },
];

