import {
  BillQueueItem,
  CashierMenuItem,
  ShiftHistoryItem,
  CashierNotification,
} from './types';

export const initialBillQueue: BillQueueItem[] = [
  {
    id: 'bq-1',
    tableNumber: 12,
    tableName: 'Table 12',
    orderNumber: 'ORD-1042',
    customerName: 'Sarah M.',
    itemsCount: 3,
    itemsDescription: 'Truffle Risotto x3',
    waitMinutes: 4,
    amountDue: 104.52,
    status: 'pending',
    isHighlighted: true,
  },
  {
    id: 'bq-2',
    tableNumber: 4,
    tableName: 'Table 4',
    orderNumber: 'ORD-1043',
    customerName: 'Michael R.',
    itemsCount: 2,
    itemsDescription: 'Prime Ribeye, Barolo Wine',
    waitMinutes: 2,
    amountDue: 78.5,
    status: 'pending',
  },
  {
    id: 'bq-3',
    tableNumber: 8,
    tableName: 'Table 8',
    orderNumber: 'ORD-1044',
    customerName: 'Emma L.',
    itemsCount: 4,
    itemsDescription: 'Sea Bass, Caesar Salad, Negroni x2',
    waitMinutes: 7,
    amountDue: 142.3,
    status: 'pending',
  },
  {
    id: 'bq-4',
    tableNumber: 3,
    tableName: 'Table 3',
    orderNumber: 'ORD-1045',
    customerName: 'David K.',
    itemsCount: 1,
    itemsDescription: 'Grilled Chicken Pieces',
    waitMinutes: 1,
    amountDue: 39.99,
    status: 'pending',
  },
  {
    id: 'bq-5',
    tableNumber: 6,
    tableName: 'Table 6',
    orderNumber: 'ORD-1046',
    customerName: 'Jessica T.',
    itemsCount: 3,
    itemsDescription: 'Vegetable Stir Fry, Truffle Fries, Sparkling Water',
    waitMinutes: 5,
    amountDue: 68.4,
    status: 'pending',
  },
  {
    id: 'bq-6',
    tableNumber: 10,
    tableName: 'Table 10',
    orderNumber: 'ORD-1047',
    customerName: 'Liam P.',
    itemsCount: 5,
    itemsDescription: 'Chef Special Set, Bordeaux 2019',
    waitMinutes: 9,
    amountDue: 215.0,
    status: 'pending',
  },
];

export const cashierMenuItems: CashierMenuItem[] = [
  {
    id: 'm-1',
    name: 'Grilled chicken pieces',
    category: 'Mains',
    price: 39.99,
    imageUrl: 'https://images.unsplash.com/photo-1598515214211-89d3c73ae83b?auto=format&fit=crop&w=400&q=80',
    description: 'Charred herb marinated farm chicken with seasonal glaze.',
  },
  {
    id: 'm-2',
    name: 'Ribeye Steak',
    category: 'Mains',
    price: 39.99,
    imageUrl: 'https://images.unsplash.com/photo-1558030006-450675393462?auto=format&fit=crop&w=400&q=80',
    description: 'Prime dry-aged cut served medium rare with bone marrow jus.',
  },
  {
    id: 'm-3',
    name: 'Vegetable Stir Fry',
    category: 'Mains',
    price: 39.99,
    imageUrl: 'https://images.unsplash.com/photo-1540420773420-3366772f4999?auto=format&fit=crop&w=400&q=80',
    description: 'Wok-tossed organic greens, baby corn, ginger soy reduction.',
  },
  {
    id: 'm-4',
    name: 'Caesar Salad',
    category: 'Starters',
    price: 14.0,
    imageUrl: 'https://images.unsplash.com/photo-1550304943-4f24f54ddde9?auto=format&fit=crop&w=400&q=80',
    description: 'Crisp romaine hearts, shaved parmigiano, garlic herb croutons.',
  },
  {
    id: 'm-5',
    name: 'Truffle Margherita Pizza',
    category: 'Mains',
    price: 22.0,
    imageUrl: 'https://images.unsplash.com/photo-1604382355076-af4b0eb60143?auto=format&fit=crop&w=400&q=80',
    description: 'San Marzano tomatoes, fior di latte, black truffle shavings.',
  },
  {
    id: 'm-6',
    name: 'Artisan Negroni Sbagliato',
    category: 'Drinks',
    price: 16.0,
    imageUrl: 'https://images.unsplash.com/photo-1514362545857-3bc16c4c7d1b?auto=format&fit=crop&w=400&q=80',
    description: 'Campari, sweet vermouth, sparkling prosecco, orange express.',
  },
  {
    id: 'm-7',
    name: 'Handcrafted Tiramisu',
    category: 'Desserts',
    price: 12.5,
    imageUrl: 'https://images.unsplash.com/photo-1571877227200-a0d98ea607e9?auto=format&fit=crop&w=400&q=80',
    description: 'Espresso-soaked savoiardi, mascarpone cream, cocoa dust.',
  },
  {
    id: 'm-8',
    name: 'Truffle Parmesan Fries',
    category: 'Sides',
    price: 9.5,
    imageUrl: 'https://images.unsplash.com/photo-1573080496219-bb080dd4f877?auto=format&fit=crop&w=400&q=80',
    description: 'Hand-cut russet fries, white truffle oil, grated pecorino.',
  },
];

export const initialShiftHistory: ShiftHistoryItem[] = [
  {
    id: 'sh-1',
    tableNumber: 12,
    tableName: 'Table 12',
    orderNumber: 'ORD-1042',
    paymentMethod: 'Credit Card',
    itemsSummary: 'Truffle Risotto ,Truffle Risotto,Truffle Risotto',
    timestamp: '04:41 PM',
    amount: 104.52,
    status: 'completed',
  },
  {
    id: 'sh-2',
    tableNumber: 5,
    tableName: 'Table 5',
    orderNumber: 'ORD-1040',
    paymentMethod: 'Credit Card',
    itemsSummary: 'Grilled Chicken Pieces, Caesar Salad, Mineral Water',
    timestamp: '04:15 PM',
    amount: 58.99,
    status: 'completed',
  },
  {
    id: 'sh-3',
    tableNumber: 9,
    tableName: 'Table 9',
    orderNumber: 'ORD-1038',
    paymentMethod: 'Apple Pay',
    itemsSummary: 'Ribeye Steak x2, Red Wine Bottle, Tiramisu',
    timestamp: '03:48 PM',
    amount: 148.0,
    status: 'completed',
  },
  {
    id: 'sh-4',
    tableNumber: 2,
    tableName: 'Table 2',
    orderNumber: 'ORD-1035',
    paymentMethod: 'Cash',
    itemsSummary: 'Vegetable Stir Fry, Green Jasmine Tea x2',
    timestamp: '03:22 PM',
    amount: 45.5,
    status: 'completed',
  },
  {
    id: 'sh-5',
    tableNumber: 7,
    tableName: 'Table 7',
    orderNumber: 'ORD-1031',
    paymentMethod: 'Credit Card',
    itemsSummary: 'Truffle Margherita Pizza, Negroni Sbagliato x2',
    timestamp: '02:55 PM',
    amount: 54.0,
    status: 'completed',
  },
];

export const initialCashierNotifications: CashierNotification[] = [
  {
    id: 'notif-1',
    title: 'Waiter James flagged Table 12 for payment.',
    timeAgo: '15m ago',
    type: 'payment',
    isActive: true,
  },
  {
    id: 'notif-2',
    title: 'Receipt paper is running low in Station 1.',
    timeAgo: '2m ago',
    type: 'hardware',
    isActive: true,
  },
  {
    id: 'notif-3',
    title: 'Tavonza System Update complete.',
    timeAgo: '1 hr ago',
    type: 'system',
    isActive: false,
  },
  {
    id: 'notif-4',
    title: 'Bar Station handoff received for Table 4.',
    timeAgo: '22m ago',
    type: 'payment',
    isActive: false,
  },
];
