import {
  DrinkOrderItem,
  BarStation,
  BeverageInventoryItem,
  BarAlert,
  AIBeverageInsight,
  BarStatCard,
} from './types';

export const mockDrinkOrders: DrinkOrderItem[] = [
  {
    id: 'd-1',
    orderNumber: '#20581',
    table: 'T-08',
    items: 'Mojito ×2',
    priority: 'High',
    eta: '3 min',
    status: 'Preparing',
    timePlaced: '10:24 AM',
    station: 'Cocktail',
  },
  {
    id: 'd-2',
    orderNumber: '#20581',
    table: 'T-08',
    items: 'Mojito ×2',
    priority: 'Medium',
    eta: '3 min',
    status: 'Preparing',
    timePlaced: '10:25 AM',
    station: 'Cocktail',
  },
  {
    id: 'd-3',
    orderNumber: '#20581',
    table: 'T-08',
    items: 'Mojito ×2',
    priority: 'Normal',
    eta: '3 min',
    status: 'Quality Check',
    timePlaced: '10:26 AM',
    station: 'Cocktail',
  },
  {
    id: 'd-4',
    orderNumber: '#20581',
    table: 'Bar Counter',
    items: 'Cappuccino ×2',
    priority: 'High',
    eta: '3 min',
    status: 'Preparing',
    timePlaced: '10:27 AM',
    station: 'Coffee',
  },
  {
    id: 'd-5',
    orderNumber: '#20582',
    table: 'T-04',
    items: 'Espresso Martini ×1 · Sparkling Water ×1',
    priority: 'High',
    eta: '4 min',
    status: 'New',
    timePlaced: '10:28 AM',
    station: 'Cocktail',
  },
  {
    id: 'd-6',
    orderNumber: '#20583',
    table: 'T-12',
    items: 'Fresh Mango Juice ×2 · Diet Coke ×1',
    priority: 'Normal',
    eta: '2 min',
    status: 'Ready',
    timePlaced: '10:22 AM',
    station: 'Juice',
  },
];

export const mockBarStations: BarStation[] = [
  {
    id: 'bs-1',
    name: 'Cocktail Station',
    activeOrders: 8,
    status: 'Busy',
    statusColor: 'text-red-400',
    dotColor: 'bg-red-500',
  },
  {
    id: 'bs-2',
    name: 'Coffee Station',
    activeOrders: 4,
    status: 'Normal',
    statusColor: 'text-yellow-500',
    dotColor: 'bg-yellow-500',
  },
  {
    id: 'bs-3',
    name: 'Soft Drinks Station',
    activeOrders: 3,
    status: 'Available',
    statusColor: 'text-emerald-500',
    dotColor: 'bg-emerald-500',
  },
  {
    id: 'bs-4',
    name: 'Juice Station',
    activeOrders: 3,
    status: 'Available',
    statusColor: 'text-emerald-500',
    dotColor: 'bg-emerald-500',
  },
];

export const mockBeverageInventory: BeverageInventoryItem[] = [
  {
    id: 'inv-1',
    name: 'Fresh Mint',
    stockStatus: 'Low Stock',
    dotColor: 'bg-red-500',
    badgeBg: 'bg-red-500/10',
    badgeText: 'text-red-400',
    badgeBorder: 'border-red-500/20',
  },
  {
    id: 'inv-2',
    name: 'Coffee Beans',
    stockStatus: 'In Stock',
    dotColor: 'bg-orange-500',
    badgeBg: 'bg-emerald-500/10',
    badgeText: 'text-emerald-500',
    badgeBorder: 'border-emerald-500/20',
  },
  {
    id: 'inv-3',
    name: 'Lemon Syrup',
    stockStatus: 'Running Low',
    dotColor: 'bg-yellow-500',
    badgeBg: 'bg-yellow-500/10',
    badgeText: 'text-yellow-500',
    badgeBorder: 'border-yellow-500/20',
  },
  {
    id: 'inv-4',
    name: 'Soft Drinks (Cans)',
    stockStatus: 'In Stock',
    dotColor: 'bg-emerald-500',
    badgeBg: 'bg-emerald-500/10',
    badgeText: 'text-emerald-500',
    badgeBorder: 'border-emerald-500/20',
  },
];

export const mockBarAlerts: BarAlert[] = [
  {
    id: 'alt-1',
    message: 'VIP beverage order #20581 must be completed within 2 minutes.',
    dotColor: 'bg-red-500',
    bgTint: 'bg-red-500/5',
    borderTint: 'border-red-500/20',
  },
  {
    id: 'alt-2',
    message: 'Fresh mint stock is below the minimum level.',
    dotColor: 'bg-orange-500',
    bgTint: 'bg-orange-500/5',
    borderTint: 'border-orange-500/20',
  },
  {
    id: 'alt-3',
    message: 'Coffee machine maintenance is due in 2 days.',
    dotColor: 'bg-yellow-500',
    bgTint: 'bg-yellow-500/5',
    borderTint: 'border-yellow-500/20',
  },
  {
    id: 'alt-4',
    message: 'Soft drink station is operating normally.',
    dotColor: 'bg-emerald-500',
    bgTint: 'bg-emerald-500/5',
    borderTint: 'border-emerald-500/20',
  },
];

export const mockAIBeverageInsights: AIBeverageInsight[] = [
  {
    id: 'ins-1',
    title: 'Popular Drinks',
    description: "Signature Mojito is today's top-selling beverage.",
  },
  {
    id: 'ins-2',
    title: 'Demand Forecast',
    description: 'Cold beverages expected to increase by 25% between 6–9 PM.',
  },
  {
    id: 'ins-3',
    title: 'Upsell Opportunity',
    description: 'Customers ordering burgers are likely to purchase soft drinks.',
  },
  {
    id: 'ins-4',
    title: 'Upsell Opportunity',
    description: 'Pairing craft mocktails with spicy appetizers increased checks by $8.20.',
  },
];

export const mockBarStatCards: BarStatCard[] = [
  {
    id: 'stat-1',
    value: '18',
    label: 'Beverage Orders',
    subtext: 'In Queue',
    shadowColor: 'shadow-[0px_0px_6px_0px_rgba(255,185,0,0.60)] border-amber-500/30',
    iconName: 'GlassWater',
  },
  {
    id: 'stat-2',
    value: '06',
    label: 'Drinks Ready',
    subtext: 'Ready for Pickup',
    shadowColor: 'shadow-[0px_0px_6px_0px_rgba(43,127,255,0.60)] border-blue-500/30',
    iconName: 'CheckCircle2',
  },
  {
    id: 'stat-3',
    value: '142',
    label: 'Drinks Served',
    subtext: 'Completed Today',
    shadowColor: 'shadow-[0px_0px_6px_0px_rgba(173,70,255,0.60)] border-purple-500/30',
    iconName: 'Wine',
  },
  {
    id: 'stat-4',
    value: '4m',
    label: 'Avg Prep Time',
    subtext: 'Per Drink',
    shadowColor: 'shadow-[0px_0px_6px_0px_rgba(0,166,62,0.60)] border-emerald-500/30',
    iconName: 'Clock',
  },
  {
    id: 'stat-5',
    value: '95%',
    label: 'Bar Efficiency',
    subtext: 'Operational Score',
    shadowColor: 'shadow-[0px_0px_6px_0px_rgba(255,255,255,0.30)] border-white/20',
    iconName: 'Sparkles',
  },
  {
    id: 'stat-6',
    value: '02',
    label: 'Delayed Orders',
    subtext: 'Require Attention',
    shadowColor: 'shadow-[0px_0px_6px_0px_rgba(239,68,68,0.50)] border-red-500/30',
    iconName: 'AlertTriangle',
  },
];
